# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harrispierce', '0002_auto_20170918_1319'),
        ('userprofile', '0002_remove_choice_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harrispierce.Article')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harrispierce.Journal')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harrispierce.Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
