# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_likedarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedarticles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harrispierce.Article', unique=True),
        ),
    ]
