# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20170921_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedarticles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harrispierce.Article', unique=True),
        ),
    ]
