# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harrispierce', '0002_auto_20170918_1319'),
        ('userprofile', '0011_auto_20171029_1809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sentarticles',
            unique_together=set([('sender', 'article', 'recipient')]),
        ),
    ]
