# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20171030_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentarticles',
            name='comment',
            field=models.TextField(default=b''),
        ),
    ]
