# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harrispierce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='article',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='section',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='following',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user_followed',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
