# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harrispierce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(default='void', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=models.TextField(default='void', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
