# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harrispierce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.TextField(default='void'),
        ),
        migrations.AddField(
            model_name='article',
            name='cleaned_article',
            field=models.TextField(default='void'),
        ),
        migrations.AddField(
            model_name='article',
            name='href',
            field=models.CharField(default='void', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='harrispierce.Journal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='teaser',
            field=models.TextField(default='void'),
        ),
        migrations.AddField(
            model_name='journal',
            name='country',
            field=models.CharField(default='void', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 1, 14, 41, 47, 25762)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='void@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(default='void'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
