# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harrispierce', '0002_auto_20170801_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
